// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func IndexPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-white/60 backdrop-blur-lg rounded-2xl shadow-lg border border-slate-200 overflow-hidden\"><div class=\"md:flex\"><div class=\"md:flex-shrink-0 p-8 flex items-center justify-center\"><div class=\"h-32 w-32 rounded-full bg-gradient-to-br from-purple-500 to-indigo-600 flex items-center justify-center shadow-md\"><span class=\"text-white text-4xl font-bold\">W</span></div></div><div class=\"p-8 pr-12\"><div class=\"uppercase tracking-wide text-sm text-indigo-600 font-bold\">Whaler</div><h1 class=\"mt-1 text-3xl font-bold text-slate-900\">Software Engineer & Blogger</h1><p class=\"mt-4 text-slate-600\">Welcome to my personal blog. I write about Go, web development, and other things I'm passionate about. Stick around to read my latest thoughts.</p></div></div></div><h2 class=\"text-3xl font-bold mt-16 mb-8 text-slate-900\">From the blog</h2><div class=\"grid grid-cols-1 md:grid-cols-2 gap-8\"><div class=\"bg-white p-8 rounded-2xl shadow-md hover:shadow-xl transition-shadow duration-300 border border-slate-200\"><h3 class=\"text-xl font-bold text-slate-900\">My First Post</h3><p class=\"text-slate-600 mt-2\">This is a summary of the first blog post. It's where I introduce myself and my goals for this blog.</p><a href=\"#\" class=\"text-indigo-600 hover:text-indigo-800 font-semibold mt-4 inline-block\">Read more &rarr;</a></div><div class=\"bg-white p-8 rounded-2xl shadow-md hover:shadow-xl transition-shadow duration-300 border border-slate-200\"><h3 class=\"text-xl font-bold text-slate-900\">Exploring Templ</h3><p class=\"text-slate-600 mt-2\">A deep dive into the templ library for Go, and why I chose it for this blog.</p><a href=\"#\" class=\"text-indigo-600 hover:text-indigo-800 font-semibold mt-4 inline-block\">Read more &rarr;</a></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("My Awesome Blog").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
